module Stem.ButtonPanelTester.Tests.Property.Can.KeyStateBitmapProperties

open FsCheck.FSharp
open FsCheck.Xunit
open Xunit
open Stem.ButtonPanelTester.Core.Can

/// Bit value (`0` / `1`) of position `i` in byte `b` — the test's own
/// independent read of the wire, kept separate from the detector under test.
let private bitValue (b: byte) (i: int) : byte = (b >>> i) &&& 1uy

/// Normalise an arbitrary `int` to a wire bit position `0..7`.
let private toBit (raw: int) : int = ((raw % 8) + 8) % 8

/// Force bit `i` of `b` to `1` — pins a generated byte to a property's
/// precondition without `==>` discards.
let private withBit (i: int) (b: byte) : byte = b ||| (1uy <<< i)

/// Force bit `i` of `b` to `0` — the complement of `withBit`.
let private withoutBit (i: int) (b: byte) : byte = b &&& ~~~(1uy <<< i)

/// Mirrors the Lean theorem `press_edge_iff_high_to_low` in
/// `Phase4/KeyStateBitmap.lean` (T003): for every position, it is reported
/// as a press edge **iff** it is active in `activeMask`, was released in
/// `prior` (bit `1`), and is pressed in `next` (bit `0`) — the firmware
/// `1 → 0` press edge (R2). The expected condition hardcodes the concrete
/// `1 → 0` wire polarity (mirroring the Lean theorem
/// `prior.testBit i = true ∧ next.testBit i = false` literally) rather than
/// reading it back through `PressedBit`, so this is an **independent** check
/// on the detector: `PressedBit` stays the detector's one-line-flip point,
/// but pinning the concrete polarity here means a wrong flip is caught
/// (the bench gate #253 confirms this direction).
[<Property>]
let PressEdgeDetectsHighToLow (activeMask: byte) (priorByte: byte) (nextByte: byte) (rawBit: int) =
    let i = toBit rawBit
    let edges = KeyStateBitmap.pressEdges activeMask (KeyStateBitmap priorByte) (KeyStateBitmap nextByte)
    let active = bitValue activeMask i = 1uy
    let priorReleased = bitValue priorByte i = 1uy
    let nextPressed = bitValue nextByte i = 0uy
    Set.contains i edges = (active && priorReleased && nextPressed)

/// Mirrors the Lean theorem `inactive_bits_ignored` (T003): a position
/// outside the active mask is never reported, whatever the two frames carry
/// (FR-014).
[<Property>]
let InactiveBitsIgnored (activeMask: byte) (priorByte: byte) (nextByte: byte) (rawBit: int) =
    let i = toBit rawBit

    (bitValue activeMask i = 0uy)
    ==> (not (
        Set.contains i (KeyStateBitmap.pressEdges activeMask (KeyStateBitmap priorByte) (KeyStateBitmap nextByte))
    ))

/// Baseline property: a single frame compared against itself yields the
/// empty edge set — no absolute byte is ever read as press-state (R2 boot
/// caveat). A bit cannot be both released in `prior` and pressed in `next`
/// when `prior = next`, so a held button or a steady-state heartbeat scores
/// nothing.
[<Property>]
let SelfFrameYieldsNoEdges (activeMask: byte) (frameByte: byte) =
    let bitmap = KeyStateBitmap frameByte
    KeyStateBitmap.pressEdges activeMask bitmap bitmap = Set.empty

/// Cold-boot example (#293, data-model §6b): a cold panel's bitmap boots
/// `0x00`, so seeding the armed state from the baseline arms nothing. The
/// FIRST press of a button never reaches the wire (clearing an already-clear
/// bit leaves `TxTasti` unchanged, so the change gate never fires —
/// `UserMain.c:1369,:973`), so no press frame exists to compare; the release
/// then flips the bit `0 → 1` and DOES transmit. The plain press-edge
/// detector can never score position 0 on that run; the §6b release rule for
/// unarmed positions scores it on the release transition.
[<Fact>]
let ColdBootFirstPressScoresOnRelease () =
    let baseline = KeyStateBitmap 0x00uy
    let armed = KeyStateBitmap.arm 0uy baseline // seed from the baseline frame: nothing armed
    let release = KeyStateBitmap 0x01uy // the release frame — the press itself was never sent

    // The plain detector reports no press edge on the only transition this run has.
    Assert.Equal<Set<int>>(Set.empty, KeyStateBitmap.pressEdges 0x01uy baseline release)

    // The §6b rule scores the unarmed position on its release transition.
    Assert.Equal<Set<int>>(Set.singleton 0, KeyStateBitmap.scoredPositions armed 0x01uy baseline release)

/// Mirrors the Lean theorem `armed_scores_on_press_edge` (T051): for a
/// position the armed state carries, the §6b rule degenerates to the plain
/// detector — it scores **iff** `pressEdges` reports the position, so
/// steady-state behaviour is exactly the pre-#293 one.
[<Property>]
let ArmedPositionScoresOnPressEdgeOnly
    (armedRaw: byte)
    (activeMask: byte)
    (priorByte: byte)
    (nextByte: byte)
    (rawBit: int)
    =
    let i = toBit rawBit
    let armed = withBit i armedRaw
    let prior = KeyStateBitmap priorByte
    let next = KeyStateBitmap nextByte
    let scored = KeyStateBitmap.scoredPositions armed activeMask prior next
    Set.contains i scored = Set.contains i (KeyStateBitmap.pressEdges activeMask prior next)

/// Mirrors the Lean theorem `unarmed_scores_on_first_release` (T051): an
/// unarmed active position with a `0 → 1` (release) transition scores — the
/// completed first press the firmware never transmitted — and folding the
/// observed `next` bitmap into the armed state arms the position.
[<Property>]
let UnarmedPositionScoresAndArmsOnFirstRelease
    (armedRaw: byte)
    (maskRaw: byte)
    (priorRaw: byte)
    (nextRaw: byte)
    (rawBit: int)
    =
    let i = toBit rawBit
    let armed = withoutBit i armedRaw
    let activeMask = withBit i maskRaw
    let next = KeyStateBitmap(withBit i nextRaw)
    let scored = KeyStateBitmap.scoredPositions armed activeMask (KeyStateBitmap(withoutBit i priorRaw)) next
    Set.contains i scored && bitValue (KeyStateBitmap.arm armed next) i = 1uy

/// Mirrors the Lean theorem `arming_monotonic` (T051): the arming fold never
/// clears a bit — whatever bitmap is observed next, an armed position stays
/// armed.
[<Property>]
let ArmingMonotonic (armedRaw: byte) (observedByte: byte) (rawBit: int) =
    let i = toBit rawBit
    let armed = withBit i armedRaw
    bitValue (KeyStateBitmap.arm armed (KeyStateBitmap observedByte)) i = 1uy

/// Mirrors the Lean theorem `no_double_score_after_arming` (T051): once an
/// unarmed position has scored via the release rule — and been armed by the
/// fold of that same frame — a later fresh `0 → 1` transition never scores it
/// again: the armed branch demands the prior bit be `1`. The unarmed rule
/// fires at most once per position.
[<Property>]
let NoDoubleScoreAfterArming
    (armedRaw: byte)
    (maskRaw: byte)
    (priorRaw: byte)
    (nextRaw: byte)
    (laterPriorRaw: byte)
    (laterNextRaw: byte)
    (rawBit: int)
    =
    let i = toBit rawBit
    let armed = withoutBit i armedRaw
    let activeMask = withBit i maskRaw
    let next = KeyStateBitmap(withBit i nextRaw)
    let firstScored = KeyStateBitmap.scoredPositions armed activeMask (KeyStateBitmap(withoutBit i priorRaw)) next
    let armedAfter = KeyStateBitmap.arm armed next

    let laterScored =
        KeyStateBitmap.scoredPositions
            armedAfter
            activeMask
            (KeyStateBitmap(withoutBit i laterPriorRaw))
            (KeyStateBitmap(withBit i laterNextRaw))

    Set.contains i firstScored && not (Set.contains i laterScored)
